name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write   # for npm provenance (recommended)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify environment
        run: |
          node --version
          pnpm --version
          pnpm config get ignore-optional
          pnpm why rolldown

      - run: pnpm turbo run typecheck test

      - run: pnpm turbo run build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
          publish: pnpm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          # GITHUB_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
